export default function TermsOfService() {
  return (
    <div
      className="fixed inset-0 overflow-y-auto font-landing-sans text-brand-cloud/90 antialiased"
      style={{
        background: `linear-gradient(165deg, var(--page-bg-a) 0%, var(--page-bg-b) 45%, #1c1917 100%)`,
      }}
    >
      <header className="border-b border-white/[0.06] bg-[rgb(24_24_27_/0.82)] backdrop-blur-lg">
        <div className="mx-auto flex max-w-3xl items-center gap-4 px-5 py-4 sm:px-8">
          <a href="/" className="flex items-center gap-3 hover:opacity-80 transition">
            <div className="flex h-9 w-9 items-center justify-center rounded-xl border border-white/10 bg-gradient-to-br from-brand-navy to-brand-slate">
              <span className="font-landing-display text-lg font-semibold tracking-tight text-brand-cloud">R</span>
            </div>
            <span className="font-landing-display text-xl font-semibold tracking-tight text-brand-cloud">Reco</span>
          </a>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-5 py-14 sm:px-8 sm:py-20">
        <h1 className="font-landing-display text-4xl font-semibold tracking-tight text-brand-cloud sm:text-5xl">
          Terms of Service
        </h1>
        <p className="mt-3 text-sm text-brand-cloud/45">Last updated: April 21, 2026</p>

        <div className="mt-12 space-y-10 text-sm leading-relaxed text-brand-cloud/70">

          <section>
            <h2 className="font-landing-display text-xl font-semibold text-brand-cloud mb-3">Acceptance of terms</h2>
            <p>
              By accessing or using Reco ("the Service"), you agree to be bound by these Terms of Service. If you do
              not agree, do not use the Service. These terms apply to all users, including free trial users and paid
              subscribers. The Service is offered for use in the United States.
            </p>
          </section>

          <section>
            <h2 className="font-landing-display text-xl font-semibold text-brand-cloud mb-3">Description of service</h2>
            <p>
              Reco is an AI-assisted productivity tool designed to help real estate professionals throughout the United
              States organize client workspaces, manage documents and email context, and draft communications. Reco
              connects to third-party AI providers (including Anthropic, OpenAI, and Google DeepMind) to generate
              responses based on the context you provide.
            </p>
          </section>

          <section className="rounded-2xl border border-amber-400/20 bg-amber-500/[0.06] p-6">
            <h2 className="font-landing-display text-xl font-semibold text-brand-cloud mb-3">
              AI responses are not professional advice
            </h2>
            <p className="text-brand-cloud/80">
              <strong className="text-brand-cloud">Reco is an AI assistant, not a licensed real estate agent, attorney, financial advisor, or
              professional of any kind.</strong> All responses generated by Reco are for informational and productivity
              purposes only.
            </p>
            <p className="mt-3">
              Nothing Reco generates — including but not limited to suggested offer language, contract terms,
              negotiation strategies, inspection responses, financing timelines, or any other deal-related content —
              constitutes legal, financial, or professional real estate advice. You should not rely solely on Reco's
              output when making decisions that affect your clients, your business, or any transaction.
            </p>
            <p className="mt-3">
              You are solely responsible for reviewing, verifying, and taking professional responsibility for any
              content you use from Reco. Always consult a licensed professional when appropriate. Reco and its
              operators are not liable for any losses, damages, errors, or outcomes resulting from actions taken in
              reliance on AI-generated content.
            </p>
          </section>

          <section>
            <h2 className="font-landing-display text-xl font-semibold text-brand-cloud mb-3">Subscriptions and billing</h2>
            <ul className="space-y-3">
              <li>
                <span className="text-brand-cloud/90 font-medium">Free tier</span> — Free accounts include limited
                AI usage and one active client workspace. No credit card is required.
              </li>
              <li>
                <span className="text-brand-cloud/90 font-medium">Paid plans</span> — Individual tiers (Pro, Max, and
                Ultra) are priced and described on our landing page and billed monthly. Paid plans include higher AI
                usage limits than Free, advanced or frontier models depending on tier, and unlimited client workspaces
                where stated. You may cancel at any time; cancellation takes effect at the end of the current billing
                period.
              </li>
              <li>
                <span className="text-brand-cloud/90 font-medium">Refunds</span> — We do not offer refunds for
                partial billing periods. If you believe you were charged in error, contact us within 30 days.
              </li>
              <li>
                <span className="text-brand-cloud/90 font-medium">Usage limits</span> — AI usage is metered. If you
                reach your monthly limit, chat will be paused until your billing period resets. We do not
                automatically charge overage fees.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="font-landing-display text-xl font-semibold text-brand-cloud mb-3">Your responsibilities</h2>
            <ul className="space-y-3">
              <li>You must be at least 18 years old and authorized to use the Service for your business purposes.</li>
              <li>You are responsible for maintaining the confidentiality of your account and for all activity under it.</li>
              <li>
                You must not use Reco to process or store information in violation of applicable privacy laws or your
                own obligations to your clients.
              </li>
              <li>You must not attempt to reverse-engineer, scrape, or abuse the Service.</li>
              <li>
                You are responsible for ensuring that any client data you upload or sync into Reco complies with your
                professional obligations and applicable regulations.
              </li>
              <li>
                You will not import or sync content in violation of third-party rights or required permissions.
              </li>
              <li>
                You are solely responsible for compliance with the &quot;Imported and synchronized content&quot;
                section below.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="font-landing-display text-xl font-semibold text-brand-cloud mb-3">Google integrations</h2>
            <p>
              Connecting Gmail or Google Drive is optional. When connected, Reco reads data from those services on
              your behalf subject to the permissions you grant. You may revoke access at any time through your{' '}
              <a
                href="https://myaccount.google.com/permissions"
                target="_blank"
                rel="noopener noreferrer"
                className="text-brand-mint hover:text-brand-cloud transition underline underline-offset-2"
              >
                Google account permissions
              </a>
              . Revoking access will disable Gmail and Drive sync features but will not delete your Reco account or
              existing data.
            </p>
            <p className="mt-3">
              Connecting Google enables Reco to sync and import messages and files from your account. Lawful use of
              that synced data—including email or files that relate to third parties—is your responsibility, as
              described in the following section.
            </p>
          </section>

          <section>
            <h2 className="font-landing-display text-xl font-semibold text-brand-cloud mb-3">
              Imported and synchronized content
            </h2>
            <p>
              You are solely responsible for determining whether you may import, sync, upload, or process messages,
              documents, and other content—including content that identifies or relates to third parties such as
              clients, other agents, lenders, or counterparties. Before bringing such content into Reco, you agree to
              obtain and maintain any permissions, consents, authorizations, or licenses required from those third
              parties and under your contracts, brokerage policies, MLS or board rules, and applicable law.
            </p>
            <p className="mt-3">
              Reco does not verify that you have obtained any third party&apos;s permission and does not monitor your
              compliance with these obligations.
            </p>
            <p className="mt-3">
              You represent and warrant that your import or synchronization of content does not violate the rights of
              any third party or your obligations to any person or entity.
            </p>
            <p className="mt-3">
              To the fullest extent permitted by law, Reco and its operators are not responsible for claims, losses,
              or disputes arising from content you import or sync, including claims by third parties that you lacked
              permission to use that content in Reco.
            </p>
          </section>

          <section>
            <h2 className="font-landing-display text-xl font-semibold text-brand-cloud mb-3">Intellectual property</h2>
            <p>
              You retain ownership of all content you upload or create in Reco. By using the Service, you grant Reco
              a limited license to process and store that content solely to provide the Service to you. We do not
              claim ownership of your client data, documents, or notes.
            </p>
            <p className="mt-3">
              The Reco application, branding, and underlying software are owned by us and protected by applicable
              intellectual property laws.
            </p>
          </section>

          <section>
            <h2 className="font-landing-display text-xl font-semibold text-brand-cloud mb-3">Limitation of liability</h2>
            <p>
              To the fullest extent permitted by law, Reco and its operators shall not be liable for any indirect,
              incidental, special, consequential, or punitive damages, including but not limited to loss of profits,
              data, business, or goodwill, arising out of or in connection with your use of the Service.
            </p>
            <p className="mt-3">
              Our total liability to you for any claim arising from these terms or your use of the Service shall not
              exceed the amount you paid us in the 12 months preceding the claim, or $100, whichever is greater. This
              cap applies to the fullest extent permitted by law, including claims or disputes to the extent they
              arise from content you imported, synced, or uploaded without adequate rights or permissions, or from
              disputes between you and third parties over such content.
            </p>
            <p className="mt-3">
              The Service is provided "as is" and "as available" without warranties of any kind, express or implied,
              including fitness for a particular purpose, accuracy, or uninterrupted availability.
            </p>
          </section>

          <section>
            <h2 className="font-landing-display text-xl font-semibold text-brand-cloud mb-3">Termination</h2>
            <p>
              You may cancel your account at any time. We reserve the right to suspend or terminate accounts that
              violate these terms, abuse the Service, or engage in fraudulent activity. Upon termination, your data
              may be deleted in accordance with our{' '}
              <a href="/privacy" className="text-brand-mint hover:text-brand-cloud transition underline underline-offset-2">
                Privacy Policy
              </a>
              .
            </p>
          </section>

          <section>
            <h2 className="font-landing-display text-xl font-semibold text-brand-cloud mb-3">Changes to these terms</h2>
            <p>
              We may update these terms from time to time. We will update the "Last updated" date at the top of this
              page. Continued use of Reco after changes constitutes your acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="font-landing-display text-xl font-semibold text-brand-cloud mb-3">Governing law</h2>
            <p>
              These terms are governed by applicable law of the United States and the laws of the State of Michigan,
              without regard to conflict of law principles. Any legal action or proceeding arising out of or relating
              to these terms or the Service shall be brought exclusively in the state or federal courts located in
              Michigan, and you consent to personal jurisdiction and venue in those courts.
            </p>
          </section>

          <section>
            <h2 className="font-landing-display text-xl font-semibold text-brand-cloud mb-3">Contact</h2>
            <p>
              Questions about these terms? Contact us at{' '}
              <a
                href="mailto:raymorremi@gmail.com"
                className="text-brand-mint hover:text-brand-cloud transition underline underline-offset-2"
              >
                raymorremi@gmail.com
              </a>
              .
            </p>
          </section>

        </div>
      </main>

      <footer className="border-t border-white/[0.06] px-5 py-8 sm:px-8">
        <div className="mx-auto max-w-3xl text-center text-xs text-brand-cloud/40">
          <p className="font-landing-display text-sm text-brand-cloud/50">Reco</p>
          <p className="mt-2">
            <a href="/" className="hover:text-brand-cloud/70 transition">← Back to home</a>
          </p>
        </div>
      </footer>
    </div>
  )
}
